window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isFirefox=/firefox/i.test(navigator.userAgent);window.isOpera=(!!window.opr&&!!window.opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')>=0;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t270_scroll(hash,offset){if(!hash)return;if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return!0}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);if('scrollBehavior' in document.documentElement.style){t_throttle(window.scrollTo({left:0,top:target,behavior:'smooth',}),500)}else{t270_scrollToEl(target)}
if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_scrollToEl(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight,);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute("data-scrollable","true");if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute("data-scrollable")}},10)}
function t602_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var indicator=rec.querySelector('.t602__indicator');if(!indicator)return;window.addEventListener('scroll',t_throttle(function(){var documentHeight=document.body.clientHeight;var windowScrollTop=document.documentElement.scrollTop;var windowHeight=window.innerHeight;var scrollPercent=(windowScrollTop/(documentHeight-windowHeight))*100;indicator.style.width=scrollPercent+'%'},100))}
function t886_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var notificationBlock=rec.querySelector('.t886');var closeButton=rec.querySelector('.t886__btn');var storageItem=notificationBlock.getAttribute('data-storage-item');var lastOpen=null;if(typeof localStorage==='object'){try{lastOpen=localStorage.getItem(storageItem)}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}}
if(!lastOpen){notificationBlock.classList.remove('t886_closed')}
if(closeButton){closeButton.addEventListener('click',function(event){notificationBlock.classList.add('t886_closed');if(typeof localStorage==='object'){try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}}
event.preventDefault()})}}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed');if(container)container.style.height='auto'}else{menu.classList.remove('t450__overflowed');if(container)container.style.height=''}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__menu__content'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t794_init(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t794'):null;var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(!hook)return;var hookLinks=document.querySelectorAll('a[href="'+hook+'"]');hookLinks=Array.prototype.filter.call(hookLinks,function(hookLink){var isSubmenuAllowed=hookLink.getAttribute('data-submenu-disallowed')!=='yes';if(isSubmenuAllowed){hookLink.classList.add('t794__tm-link');hookLink.setAttribute('data-tooltip-menu-id',recid);return!0}
return!1});t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t794_highlight()}
function t794_setUpMenu(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenu=rec?rec.querySelector('.t794__tooltip-menu'):null;if(!submenu)return;var content=submenu.querySelector('.t794__content');if(window.isMobile){t794_setUpMenu_mobile(recid,hookLinks,submenu)}else{t794_setUpMenu_desktop(recid,hookLinks,submenu)}
window.addEventListener('scroll',t_throttle(function(){if(content){content.addEventListener('mouseleave',function(){if(submenu.classList.contains('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}})}},300));var tooltipLinks=document.querySelectorAll('.t794__tooltip-menu a[href*="#"]');Array.prototype.forEach.call(tooltipLinks,function(tooltipLink){tooltipLink.addEventListener('click',function(){t794_hideSubmenu(submenu);var menuList=document.querySelectorAll('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466');Array.prototype.forEach.call(menuList,function(menu){var event=document.createEvent('Event');event.initEvent('clickedAnchorInTooltipMenu',!0,!0);menu.dispatchEvent(event)});Array.prototype.forEach.call(tooltipLinks,function(link){link.classList.remove('t-active')});tooltipLink.classList.add('t-active')})})}
function t794_setUpMenu_mobile(recid,hookLinks,submenu){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t794'):null;if(!menu)return;var verticalIndent=menu?menu.getAttribute('data-tooltip-margin'):'';hookLinks.forEach(function(hookLink){hookLink.addEventListener('click',function(e){e.preventDefault();if(submenu&&submenu.classList.contains('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}else{t794_showSubmenu(hookLink,submenu,verticalIndent)}})});document.addEventListener('click',function(e){var currentAnchor=e.target.closest('.t794__tm-link');if(currentAnchor&&currentAnchor.getAttribute('data-tooltip-menu-id')!==recid&&submenu&&submenu.classList.contains('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}
var insideMenu=e.target.closest('.t794__tooltip-menu');if(!insideMenu&&!currentAnchor&&submenu&&submenu.classList.contains('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}})}
function t794_setUpMenu_desktop(recid,hookLinks,submenu){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t794'):null;var verticalIndent=menu?menu.getAttribute('data-tooltip-margin'):'';var timer;var hooksAndSubmenu=hookLinks.concat(submenu);hooksAndSubmenu.forEach(function(el){el.addEventListener('mouseover',function(){if(el.classList.contains('t794__tooltip-menu')&&!el.classList.contains('t794__tooltip-menu_show'))return;if(timer)clearTimeout(timer);if(el.classList.contains('t794__tooltip-menu')&&el.classList.contains('t794__tooltip-menu_show'))return;t794_showSubmenu(el,submenu,verticalIndent)});el.addEventListener('mouseout',function(){timer=setTimeout(function(){t794_hideSubmenu(submenu)},300)})});hookLinks.forEach(function(hookLink){hookLink.addEventListener('click',function(e){e.preventDefault()})})}
function t794_showSubmenu(currentAnchor,submenu,verticalIndent){submenu.style.display='block';var submenuHeight=submenu.offsetHeight;var submenuWidth=submenu.offsetWidth;submenu.style.display='';var anchorHeight=t794_getValueWithoutPadding(currentAnchor,'height');var anchorWidth=t794_getValueWithoutPadding(currentAnchor,'width');if(currentAnchor.classList.contains('t-btn')){anchorWidth=currentAnchor.offsetWidth}
var scrollTop=window.pageYOffset;var anchorLeft=currentAnchor.getBoundingClientRect().left+window.pageXOffset;var anchorTop=currentAnchor.getBoundingClientRect().top+window.pageYOffset;var parentZeroMenu=currentAnchor.closest('.t396__artboard');if(parentZeroMenu&&parentZeroMenu.classList.contains('t396__artboard_scale')&&window.tn_scale_factor&&!window.isFirefox&&!window.isOpera){anchorTop*=window.tn_scale_factor}
submenu.setAttribute('data-pos-fixed','no');var parentMenu=currentAnchor.closest('[data-menu="yes"]');if(parentMenu&&(parentMenu.style.position==='fixed'||window.getComputedStyle(parentMenu).position==='fixed')){submenu.setAttribute('data-pos-fixed','yes')}
var menuFixed=submenu.getAttribute('data-pos-fixed');var submenuContent=submenu.querySelector('.t794__content');if(verticalIndent){verticalIndent=parseInt(verticalIndent,10);verticalIndent+=10}
var axisY;if(menuFixed==='yes'){axisY=(anchorTop-scrollTop)+anchorHeight+verticalIndent;submenu.style.position='fixed';submenu.classList.remove('t794__tooltip-menu_top');submenu.classList.add('t794__tooltip-menu_bottom');if(submenuContent)submenuContent.maxHeight='calc(100vh - '+axisY+'px)'}else{axisY=anchorTop+anchorHeight+verticalIndent;submenu.style.position='absolute';var topSpace=anchorTop-scrollTop;var bottomSpace=window.innerHeight-topSpace;if(axisY+submenuHeight>scrollTop+window.innerHeight&&topSpace>bottomSpace){axisY=axisY-submenuHeight-anchorHeight-verticalIndent*2;submenu.classList.remove('t794__tooltip-menu_bottom');submenu.classList.add('t794__tooltip-menu_top')}else{submenu.classList.remove('t794__tooltip-menu_top');submenu.classList.add('t794__tooltip-menu_bottom')}}
var axisX=anchorLeft;if(parentZeroMenu&&parentZeroMenu.classList.contains('t396__artboard_scale')&&window.tn_scale_factor){axisX=window.isFirefox||window.isOpera?axisX:axisX*window.tn_scale_factor;anchorWidth=anchorWidth*window.tn_scale_factor}
if(axisX+submenuWidth/2<window.innerWidth){axisX=axisX+(anchorWidth-submenuWidth)/2;if(axisX<0){axisX=10}}else{axisX=window.innerWidth-submenuWidth-10}
submenu.style.display='block';submenu.style.left=axisX+'px';submenu.style.top=axisY+'px';submenu.offsetHeight;submenu.classList.add('t794__tooltip-menu_show');currentAnchor.classList.add('t794__tm-link_active')}
function t794_hideSubmenu(submenu){submenu.style.display='';submenu.style.left='';submenu.style.top='';submenu.classList.remove('t794__tooltip-menu_show');var activeLinks=document.querySelectorAll('.t794__tm-link_active');Array.prototype.forEach.call(activeLinks,function(activeLink){activeLink.classList.remove('t794__tm-link_active')})}
function t794_addArrow(recid,hookLinks){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t794'):null;var isArrowAppend=menu.getAttribute('data-add-arrow');if(!isArrowAppend)return;hookLinks.forEach(function(hookLink){var arrow=document.createElement('div');arrow.classList.add('t794__arrow');hookLink.appendChild(arrow);var isZero=hookLink.classList.contains('tn-atom');var hasCustomBorderColor=window.getComputedStyle(hookLink).borderColor!=='rgba(0, 0, 0, 0)';if(isZero&&!hasCustomBorderColor){hookLink.style.borderColor='initial';hookLink.style.border='none'}})}
function t794_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t794__list_item a[href=\''+url+'\'], '+'.t794__list_item a[href=\''+url+'/\'], '+'.t794__list_item a[href=\''+pathname+'\'], '+'.t794__list_item a[href=\'/'+pathname+'\'], '+'.t794__list_item a[href=\''+pathname+'/\'], '+'.t794__list_item a[href=\'/'+pathname+'/\']'+(hash?', .t794__list_item a[href="'+hash+'"]':''));Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t794_getValueWithoutPadding(el,value){if(!el)return 0;var elWidth=el.offsetWidth||parseInt(window.getComputedStyle(el).width,10);var elHeight=el.offsetHeight||parseInt(window.getComputedStyle(el).height,10);switch(value){case 'width':var paddingLeft=el.style.paddingLeft||parseInt(window.getComputedStyle(el).paddingLeft,10);var paddingRight=el.style.paddingLeft||parseInt(window.getComputedStyle(el).paddingRight,10);return elWidth-(paddingLeft+paddingRight);case 'height':var paddingTop=el.style.paddingTop||parseInt(window.getComputedStyle(el).paddingTop,10);var paddingBottom=el.style.paddingBottom||parseInt(window.getComputedStyle(el).paddingBottom,10);return elHeight-(paddingTop+paddingBottom)}}
function t397_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var tildaLazyMode=allRecords?allRecords.getAttribute('data-tilda-lazy'):'';var tabs=rec?rec.querySelectorAll('.t397__tab'):[];if(tildaMode!=='edit'&&tildaMode!=='preview'){t397_scrollToTabs(recid)}
Array.prototype.forEach.call(tabs,function(tab,i){tab.setAttribute('data-tab-index',i);tab.addEventListener('click',function(e){var targetTab=e.target.closest('.t397__tab');if(targetTab&&targetTab.classList.contains('t397__tab_active')&&!e.isTrusted)return;var activeTab=rec.querySelector('.t397__tab_active');if(activeTab)activeTab.classList.remove('t397__tab_active');targetTab.classList.add('t397__tab_active');t397_removeUrl();var tabNumber=i+1;if(tildaMode!=='edit'&&tildaMode!=='preview'&&tabNumber&&typeof history.replaceState!=='undefined'){try{window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}catch(err){}}
t397_alltabs_updateContent(recid);t397_updateSelect(recid);var hookBlocks=targetTab.getAttribute('data-tab-rec-ids').split(',');var event=document.createEvent('Event');event.initEvent('displayChanged',!0,!0);hookBlocks.forEach(function(curRecid){var currentRec=document.getElementById('rec'+curRecid);if(!currentRec)return;var currentRecChildren=currentRec.querySelectorAll('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t448, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t569, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t902, .t912, .t923, .t937, .t959, .t979, .t982, .t983, .t989, .t994');Array.prototype.forEach.call(currentRecChildren,function(child){child.dispatchEvent(event)});var displayChangedBlock=currentRec.querySelector('[data-display-changed="true"]');if(displayChangedBlock)displayChangedBlock.dispatchEvent(event)});var galaxyEffectBlocks=document.querySelectorAll('.t826');Array.prototype.forEach.call(galaxyEffectBlocks,function(galaxyEffectBlock){galaxyEffectBlock.dispatchEvent(event)});t397_startUpdateLazyLoad(targetTab);if(window.lazy==='y'||tildaLazyMode==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});if(tabs.length){t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid);var bgColor=rec?rec.style.backgroundColor:'#ffffff';var bgColorTargets=rec.querySelectorAll('.t397__select, .t397__firefoxfix');Array.prototype.forEach.call(bgColorTargets,function(target){target.style.background=bgColor})}
document.addEventListener('click',function(e){if(e.target.closest('[href*="#!/tab/'+recid+'"]')){var currentLink=e.target.closest('[href*="#!/tab/'+recid+'"]');var hash=currentLink.hash;t397_scrollToTabs(recid,hash)}})}
function t397_alltabs_updateContent(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var tabs=Array.prototype.slice.call(rec.querySelectorAll('.t397__tab:not(.t397__tab_active)'));var activeTab=rec.querySelector('.t397__tab_active');var select=rec.querySelector('.t397__select');if(!activeTab)return;var hookBlocks=activeTab.getAttribute('data-tab-rec-ids').split(',');var noActive=[];Array.prototype.forEach.call(tabs,function(tab){if(tab!==activeTab){var noActiveHooks=tab.getAttribute('data-tab-rec-ids').split(',');noActiveHooks.forEach(function(hook){if(noActive.indexOf(hook)===-1&&hookBlocks.indexOf(hook)===-1)noActive.push(hook)})}});if(t397_checkVisibillityEl(activeTab)||t397_checkVisibillityEl(select)){hookBlocks.forEach(function(hook){if(!hook)return;var hookEl=document.getElementById('rec'+hook);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl)hookEl.classList.remove('t397__off');if(hookEl)hookEl.style.opacity='';t397_updateTabsByHook(hookElRecordType,hookEl,hook,recid)})}else{hookBlocks.forEach(function(hook){var hookEl=document.getElementById('rec'+hook);if(hookEl)hookEl.setAttribute('data-animationappear','off');if(hookEl)hookEl.classList.add('t397__off')})}
noActive.forEach(function(noActiveID){if(!noActiveID)return;var hookEl=document.getElementById('rec'+noActiveID);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl)hookEl.setAttribute('data-connect-with-tab','yes');if(hookEl)hookEl.setAttribute('data-animationappear','off');if(hookEl)hookEl.classList.add('t397__off');t397_updateTabsByHook(hookElRecordType,hookEl,noActiveID,recid)});var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(scrollHeight-window.innerHeight<window.pageYOffset){window.scrollTo(0,0)}}
function t397_updateTabsByHook(hookElRecordType,hookEl,currentID,recid){var hookElTab;switch(hookElRecordType){case '395':if(window.t395_alltabs_updateContent&&window.t395_updateSelect&&recid!==currentID){window.t395_alltabs_updateContent(currentID);window.t395_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t395__tab'):null;if(hookElTab)hookElTab.click()}
break;case '397':if(recid!==currentID){t397_alltabs_updateContent(currentID);t397_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t397__tab'):null;if(hookElTab)hookElTab.click()}
break}}
function t397_checkVisibillityEl(el){return!!(el&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length))}
function t397_updateContentBySelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var select=rec.querySelector('.t397__select');if(select){select.addEventListener('change',function(){var tabIndex=rec.querySelector('.t397__tab[data-tab-rec-ids=\''+select.value+'\'][data-tab-index="'+select.selectedIndex+'"]');if(tabIndex)tabIndex.click()})}}
function t397_updateSelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var activeTab=rec.querySelector('.t397__tab_active');var currentTabHooks=activeTab?activeTab.getAttribute('data-tab-index'):'';var select=rec.querySelector('.t397__select');if(select)select.selectedIndex=currentTabHooks}
function t397_startUpdateLazyLoad(el){var hookBlocks=el?el.getAttribute('data-tab-rec-ids').split(','):[];hookBlocks.forEach(function(hook){var rec=document.getElementById('rec'+hook);if(!rec)return;var videos=rec.querySelectorAll('.t-video-lazyload');if(videos.length){t397_updateVideoLazyLoad(videos)}})}
function t397_updateVideoLazyLoad(videos){setTimeout(function(){Array.prototype.forEach.call(videos,function(video){if(!video.classList.contains('t-video__isload')){var heightAttribute=video.getAttribute('data-videolazy-height');var height=heightAttribute?heightAttribute:'100%';if(height.indexOf('vh')!==-1)height='100%';var videoID=video.getAttribute('data-videolazy-id');videoID=videoID?videoID.trim():'';var blockID=video.getAttribute('data-blocklazy-id');var twoIdAttr=video.getAttribute('data-videolazy-two-id');var videoTwoID=twoIdAttr?'_'+twoIdAttr+'_':'';if(video.getAttribute('data-videolazy-type')==='youtube'){var oldIframe=video.querySelector('iframe');if(oldIframe&&oldIframe.parentNode)oldIframe.parentNode.removeChild(oldIframe);var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+videoTwoID+blockID;iframe.width='100%';iframe.height=height;iframe.src='https://www.youtube.com/embed/'+videoID+'?rel=0&fmt=18&html5=1&showinfo=0';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');video.insertAdjacentElement('beforeend',iframe)}}
video.classList.add('t-video__isload')})},2)}
function t397_scrollToTabs(recid,hash){var rec=document.getElementById('rec'+recid);var curUrl=hash||window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');if(tabIndexNumber===-1)return!1;var tabIndexNumberStart=curUrl.indexOf('tab/');var firstOptionSelect=rec?rec.querySelector('.t397__wrapper_mobile .t397__select option'):null;if(firstOptionSelect)firstOptionSelect.selected=!1;var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(tabRec!==recid)return!1;var tabBlock=rec?rec.querySelector('.t397'):null;var tabNumber=parseInt(curUrl.slice(tabIndexNumberStart+4+recid.length+1),10);var tabs=rec.querySelectorAll('.t397__tab');Array.prototype.forEach.call(tabs,function(tab,i){if(i===tabNumber-1){tab.click();tab.classList.add('t397__tab_active')}else{tab.classList.remove('t397__tab_active')}});var tabsMob=rec.querySelectorAll('.t397__wrapper_mobile .t397__select option');var activeTabMob=tabsMob.length?tabsMob[tabNumber-1]:null;if(activeTabMob)activeTabMob.selected=!0;setTimeout(function(){var targetOffset=tabBlock.getBoundingClientRect().top+window.pageYOffset;var target=window.innerWidth>960?targetOffset-200:targetOffset-100;if(target<0)target=0;t397_scrollToEl(target)},50)}
function t397_scrollToEl(elTopPos){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(elTopPos>bottomViewportPoint)elTopPos=bottomViewportPoint;if(elTopPos===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(elTopPos-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(elTopPos-currentPosition<0&&window.pageYOffset<=elTopPos||elTopPos-currentPosition>0&&window.pageYOffset>=elTopPos){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}
function t397_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(indexToRemove===-1){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!==-1){if(typeof history.replaceState!='undefined'){try{window.history.replaceState('','',curUrl)}catch(err){}}}}
function t674_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var backgroundImage=rec.querySelector('.t674__img-holder');if(!backgroundImage)return;backgroundImage.onload=function(){var delay=0;var allRecords=document.getElementById('allrecords');if(allRecords.getAttribute('data-blocks-animationoff')!=='yes'){delay=600}
setTimeout(function(){document.body.classList.add('t674__body_with-bg')},delay)};var event=document.createEvent('HTMLEvents');event.initEvent('load',!0,!1);backgroundImage.dispatchEvent(event)}
function t390_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var escapeEvent=t390_escClosePopup.bind(this,recId);if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t390_showPopup(recId,escapeEvent);t390_resizePopup(recId);t390__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t390__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t390_closePopup(recId,escapeEvent)});popupCloseBtn.addEventListener('click',function(){t390_closePopup(recId,escapeEvent)});for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup(recId,escapeEvent);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){document.body.classList.add('t-body_popupshowed')},300)}}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){var selects='a[href^="#"]:not([href="#"]):not([href^="#price"]):not([href^="#popup"]):not([href^="#prodpopup"]):not([href^="#order"]):not([href^="#!"]),'+'a[href^="'+curPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"]),'+'a[href^="'+curFullPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"])';var selectors=rec.querySelectorAll(selects);for(var i=0;i<selectors.length;i++){selectors[i].addEventListener('click',function(event){var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}
function t390_escClosePopup(recId){if(arguments[1].key==='Escape')t390_closePopup(recId,escapeEvent)}}
function t390_showPopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var documentBody=document.body;popup.style.display='block';setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t390__body_popupshowed');document.addEventListener('keydown',escapeEvent)}
function t390_closePopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupActive=document.querySelector('.t-popup.t-popup_show');if(popup===popupActive){document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t390__body_popupshowed')}
popup.classList.remove('t-popup_show');setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',escapeEvent)}
function t390_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}