function t190_scrollToTop(){var duration=700;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=0-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t190__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t190__animateScroll(){currentTime+=increment;window.scrollTo(0,t190__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t190__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t190__animateScroll()}
function t270_scroll(hash,offset,speed){if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var root=$('html, body');var target="";if(speed===undefined){speed=400}
try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
var isHistoryChangeAllowed=window.location.hash!==hash;var complete=function(){if(!isHistoryChangeAllowed){return}
if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
var dontChangeHistory=Boolean($('.t270').attr('data-history-disabled'));if(dontChangeHistory){complete=function(){}}
root.animate({scrollTop:target.offset().top-offset},speed,complete);return!0}
function t390_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var escapeEvent=t390_escClosePopup.bind(this,recId);if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t390_showPopup(recId,escapeEvent);t390_resizePopup(recId);t390__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t390__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t390_closePopup(recId,escapeEvent)});popupCloseBtn.addEventListener('click',function(){t390_closePopup(recId,escapeEvent)});for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup(recId,escapeEvent);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){document.body.classList.add('t-body_popupshowed')},300)}}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){var selects='a[href^="#"]:not([href="#"]):not([href^="#price"]):not([href^="#popup"]):not([href^="#prodpopup"]):not([href^="#order"]):not([href^="#!"]),'+'a[href^="'+curPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"]),'+'a[href^="'+curFullPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"])';var selectors=rec.querySelectorAll(selects);for(var i=0;i<selectors.length;i++){selectors[i].addEventListener('click',function(event){var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}
function t390_escClosePopup(recId){if(arguments[1].key==='Escape')t390_closePopup(recId,escapeEvent)}}
function t390_showPopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var documentBody=document.body;popup.style.display='block';setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t390__body_popupshowed');document.addEventListener('keydown',escapeEvent)}
function t390_closePopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupActive=document.querySelector('.t-popup.t-popup_show');if(popup===popupActive){document.body.classList.remove('t-body_popupshowed')}
popup.classList.remove('t-popup_show');setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',escapeEvent)}
function t390_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t396_init(recid){var data='';var resolution=t396_detectResolution();var allRecords=document.getElementById('allrecords');var record=document.getElementById('rec'+recid);var zeroBlock=record?record.querySelector('.t396'):null;var artBoard=record?record.querySelector('.t396__artboard'):null;window.tn_window_width=document.documentElement.clientWidth;window.tn_scale_factor=Math.round((window.tn_window_width/resolution)*100)/100;t396_initTNobj();t396_switchResolution(resolution);t396_updateTNobj();t396_artboard_build(data,recid);var isTouchDevice='ontouchend' in document;window.addEventListener('resize',function(){tn_console('>>>> t396: Window on Resize event >>>>');t396_waitForFinalEvent(function(){if(window.isMobile||isTouchDevice){if(document.documentElement.clientWidth!==window.tn_window_width){t396_doResize(recid)}}else{t396_doResize(recid)}},500,'resizeruniqueid'+recid)});window.addEventListener('orientationchange',function(){tn_console('>>>> t396: Orient change event >>>>');t396_waitForFinalEvent(function(){t396_doResize(recid)},600,'orientationuniqueid'+recid)});window.addEventListener('load',function(){t396_allelems__renderView(artBoard);var blockOverflow=artBoard?window.getComputedStyle(artBoard).getPropertyValue('overflow'):'';if(typeof t_lazyload_update==='function'&&blockOverflow==='auto'&&artBoard){artBoard.addEventListener('scroll',t_throttle(function(){var dataLazy=allRecords?allRecords.getAttribute('data-tilda-lazy'):null;if(window.lazy==='y'||dataLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}
if(window.location.hash!==''&&blockOverflow==='visible'){if(artBoard)artBoard.style.overflow='hidden';setTimeout(function(){if(artBoard)artBoard.style.overflow='visible'},1)}});if(document.querySelector('.t830')){window.addEventListener('load',function(){if(allRecords.classList.contains('t830__allrecords_padd')){t396_doResize(recid)}})}
if(record&&zeroBlock&&artBoard&&record.getAttribute('data-connect-with-tab')==='yes'){zeroBlock.addEventListener('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)});$(zeroBlock).bind('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)})}
setTimeout(function(){if(record&&record.closest('#allrecordstable')&&zeroBlock&&artBoard){zeroBlock.addEventListener('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)});$(zeroBlock).bind('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)})}},1000);if(window.isSafari&&zeroBlock){zeroBlock.classList.add('t396_safari')}
var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';var isTildaModeEdit=allRecords?allRecords.getAttribute('data-tilda-mode')==='edit':null;if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_isOnlyScalableBrowser(){var isFirefox=navigator.userAgent.search('Firefox')!==-1;var isOpera=(!!window.opr&&!!window.opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')!==-1;return isFirefox||isOpera}
function t396_scaleBlock(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var resolution=t396_detectResolution();var record=document.getElementById('rec'+recid);var elements=record?record.querySelectorAll('.t396__elem'):[];var artBoard=record?record.querySelector('.t396__artboard'):null;if(artBoard){var artBoardWidth=artBoard.clientWidth;var updatedBlockHeight=Math.floor(artBoard.clientHeight*window.tn_scale_factor);var artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');window.tn_scale_offset=(artBoardWidth*window.tn_scale_factor-artBoardWidth)/2;if(artBoardHeightVH){var artBoardMinHeight=t396_ab__getFieldValue(artBoard,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoard);var scaledMinHeight=artBoardMinHeight*window.tn_scale_factor;updatedBlockHeight=(scaledMinHeight>=artBoardMaxHeight)?scaledMinHeight:artBoardMaxHeight}
artBoard.classList.add('t396__artboard_scale');var styleStr='<style class="t396__scale-style">'+'.t-rec#rec'+recid+' { overflow: visible; }'+'#rec'+recid+' .t396__carrier,'+'#rec'+recid+' .t396__filter,'+'#rec'+recid+' .t396__artboard {'+'height: '+updatedBlockHeight+'px !important;'+'width: 100vw !important;'+'max-width: 100%;'+'}'+'</style>';artBoard.insertAdjacentHTML('beforeend',styleStr)}
Array.prototype.forEach.call(elements,function(elem){var atom=elem.querySelector('.tn-atom');var containerProp=t396_elem__getFieldValue(elem,'container');if(containerProp==='grid'){if(isOnlyScalable){if(atom){var atomParent=atom.parentNode;var div=document.createElement('div');div.classList.add('tn-atom__scale-wrapper');div.style.transform='scale('+window.tn_scale_factor+')';if(atomParent)atomParent.removeChild(atom);div.appendChild(atom);if(atomParent)atomParent.appendChild(div)}}else{elem.style.zoom=window.tn_scale_factor;if(elem.getAttribute('data-elem-type')==='shape'){var elemHeight=t396_elem__getFieldValue(elem,'height');var elemWidth=t396_elem__getFieldValue(elem,'width');var elemStyles=window.getComputedStyle(atom);var elemColor=elemStyles.backgroundColor;var elemBorder=elemStyles.borderWidth;if((elemHeight<=2||elemWidth<=2)&&elemBorder==='0px'){elem.innerHTML='<svg class="tn-atom" xmlns="http://www.w3.org/2000/svg" width="'+elemWidth+'" height="'+elemHeight+'" viewBox="0 0 '+elemWidth+' '+elemHeight+'" fill="none">'+'<rect width="'+elemWidth+'" height="'+elemHeight+'" fill="'+elemColor+'"/>'+'</svg>';var svg=elem.querySelector('svg');svg.style.backgroundColor='unset';svg.style.display='block';if(elemHeight<=2){svg.style.marginLeft='-'+elemHeight+'px';svg.style.marginTop='-'+elemHeight+'px'}
if(elemWidth<=2){svg.style.marginLeft='-'+elemWidth+'px';svg.style.marginTop='-'+elemWidth+'px'}}}
if(elem.getAttribute('data-elem-type')==='text'&&resolution<1200&&atom){atom.style.webkitTextSizeAdjust='auto'}
if(atom)atom.style.transformOrigin='center'}}})}
function t396_doResize(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var record=document.getElementById('rec'+recid);var allRecords=document.getElementById('allrecords');var resolution=t396_detectResolution();var scaleStyle=record?record.querySelector('.t396__scale-style'):null;t396_removeElementFromDOM(scaleStyle);if(!isOnlyScalable){var elements=record?record.querySelectorAll('.t396__elem'):[];Array.prototype.forEach.call(elements,function(element){element.style.zoom='';var atom=element.querySelector('.tn-atom');if(atom)atom.style.transformOrigin=''})}else{var atoms=record?record.querySelectorAll('.tn-atom'):[];Array.prototype.forEach.call(atoms,function(atom){var atomWrapper=atom.closest('.tn-atom__scale-wrapper');var atomParent=atomWrapper?atomWrapper.parentNode:null;if(atomParent)atomParent.removeChild(atomWrapper);if(atomParent)atomParent.appendChild(atom)})}
var artBoard=record?record.querySelector('.t396__artboard'):null;var artBoardWidth=artBoard?artBoard.clientWidth:0;window.tn_window_width=window.isMobile?document.documentElement.clientWidth:window.innerWidth;window.tn_scale_factor=Math.round((window.tn_window_width/resolution)*100)/100;window.tn_scale_offset=(artBoardWidth*window.tn_scale_factor-artBoardWidth)/2;t396_switchResolution(resolution);t396_updateTNobj();t396_ab__renderView(artBoard);t396_allelems__renderView(artBoard);var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';if(isScaled&&tildaMode!=='edit')t396_scaleBlock(recid)}
function t396_detectResolution(){var windowWidth=window.isMobile?document.documentElement.clientWidth:window.innerWidth;var resolution=1200;var breakpoints=[1200,960,640,480,320];for(var i=0;i<breakpoints.length-1;i++){if(windowWidth<breakpoints[i]){resolution=breakpoints[i+1]}}
return resolution}
function t396_initTNobj(){tn_console('func: initTNobj');window.tn={};window.tn.canvas_min_sizes=['320','480','640','960','1200'];window.tn.canvas_max_sizes=['480','640','960','1200',''];window.tn.ab_fields=['height','width','bgcolor','bgimg','bgattachment','bgposition','filteropacity','filtercolor','filteropacity2','filtercolor2','height_vh','valign']}
function t396_updateTNobj(){tn_console('func: updateTNobj');var allRecords=document.getElementById('allrecords');var allRecPaddingLeft=allRecords?window.getComputedStyle(allRecords).paddingLeft||'0':'0';allRecPaddingLeft=parseInt(allRecPaddingLeft,10);var allRecPaddingRight=allRecords?window.getComputedStyle(allRecords).paddingRight||'0':'0';allRecPaddingRight=parseInt(allRecPaddingRight,10);if(window.zero_window_width_hook&&window.zero_window_width_hook==='allrecords'&&allRecords){window.tn.window_width=allRecords.clientWidth-(allRecPaddingLeft+allRecPaddingRight)}else{window.tn.window_width=document.documentElement.clientWidth}
window.tn.window_height=document.documentElement.clientHeight;window.tn.curResolution;var breakpoints=[1200,960,640,480,320];for(var i=0;i<breakpoints.length;i++){if(+window.tn.curResolution===breakpoints[i]){window.tn.canvas_min_width=breakpoints[i];window.tn.canvas_max_width=i===0?window.tn.window_width:breakpoints[i-1]}}
window.tn.grid_width=window.tn.canvas_min_width;window.tn.grid_offset_left=(window.tn.window_width-window.tn.grid_width)/2}
var t396_waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){if(!uniqueId){uniqueId='Don\'t call this twice without a uniqueId'}
if(timers[uniqueId]){clearTimeout(timers[uniqueId])}
timers[uniqueId]=setTimeout(callback,ms)}})();function t396_switchResolution(resolution,resolutionMax){tn_console('func: switchResolution');if(typeof resolutionMax==='undefined'){var breakpoints=[1200,960,640,480,320];breakpoints.forEach(function(breakpoint,i){if(+resolution===breakpoint){resolutionMax=i===0?'':breakpoints[i-1]}})}
window.tn.curResolution=resolution;window.tn.curResolution_max=resolutionMax}
function t396_artboard_build(data,recid){tn_console('func: t396_artboard_build. Recid:'+recid);tn_console(data);var record=document.getElementById('rec'+recid);var allRecords=document.getElementById('allrecords');var artBoard=record?record.querySelector('.t396__artboard'):null;if(!artBoard)return!1;t396_ab__renderView(artBoard);var elements=artBoard.querySelectorAll('.tn-elem');Array.prototype.forEach.call(elements,function(element){var dataType=element.getAttribute('data-elem-type');switch(dataType){case 'text':t396_addText(artBoard,element);break;case 'image':t396_addImage(artBoard,element);break;case 'shape':t396_addShape(artBoard,element);break;case 'button':t396_addButton(artBoard,element);break;case 'video':t396_addVideo(artBoard,element);break;case 'html':t396_addHtml(artBoard,element);break;case 'tooltip':t396_addTooltip(artBoard,element);break;case 'form':t396_addForm(artBoard,element);break;case 'gallery':t396_addGallery(artBoard,element);break}});artBoard.classList.remove('rendering');artBoard.classList.add('rendered');var artBoardOverflow=artBoard.getAttribute('data-artboard-ovrflw');if((artBoardOverflow==='visible'||artBoardOverflow==='visibleX')&&allRecords){allRecords.style.overflow='hidden'}
if(artBoardOverflow==='auto'){var diff=Math.abs(artBoard.offsetHeight-artBoard.clientHeight);if(diff!==0){artBoard.style.paddingBottom=diff+'px'}}
if(window.isMobile){var style=document.createElement('style');style.textContent='@media only screen and (min-width:1366px) and (orientation:landscape) and (-webkit-min-device-pixel-ratio:2) {.t396__carrier {background-attachment:scroll!important;}}';record.insertAdjacentElement('beforeend',style)}}
function t396_ab__renderView(artBoard){if(!artBoard)return!1;var fields=window.tn.ab_fields;var allRecords=document.getElementById('allrecords');var artBoardHeightVH;for(var i=0;i<fields.length;i++){t396_ab__renderViewOneField(artBoard,fields[i])}
var artBoardMinHeight=t396_ab__getFieldValue(artBoard,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoard);var isTildaModeEdit=allRecords?allRecords.getAttribute('data-tilda-mode')==='edit':!1;var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');if(isScaled&&!isTildaModeEdit&&artBoardHeightVH){var scaledMinHeight=parseInt(artBoardMinHeight,10)*window.tn_scale_factor}
var offsetTop;if(artBoardMinHeight===artBoardMaxHeight||(scaledMinHeight&&scaledMinHeight>=artBoardMaxHeight)){offsetTop=0}else{var artBoardVerticalAlign=t396_ab__getFieldValue(artBoard,'valign');switch(artBoardVerticalAlign){case 'top':offsetTop=0;break;case 'center':if(scaledMinHeight){offsetTop=parseFloat(((artBoardMaxHeight-scaledMinHeight)/2).toFixed(1))}else{offsetTop=parseFloat(((artBoardMaxHeight-artBoardMinHeight)/2).toFixed(1))}
break;case 'bottom':if(scaledMinHeight){offsetTop=parseFloat((artBoardMaxHeight-scaledMinHeight).toFixed(1))}else{offsetTop=parseFloat((artBoardMaxHeight-artBoardMinHeight).toFixed(1))}
break;case 'stretch':offsetTop=0;artBoardMinHeight=artBoardMaxHeight;break;default:offsetTop=0;break}}
artBoard.setAttribute('data-artboard-proxy-min-offset-top',offsetTop);artBoard.setAttribute('data-artboard-proxy-min-height',artBoardMinHeight);artBoard.setAttribute('data-artboard-proxy-max-height',artBoardMaxHeight);var filter=artBoard.querySelector('.t396__filter');var carrier=artBoard.querySelector('.t396__carrier');artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');artBoardHeightVH=parseFloat(artBoardHeightVH);if(window.isMobile&&artBoardHeightVH){var height=document.documentElement.clientHeight*artBoardHeightVH/100;artBoard.style.height=height+'px';if(filter)filter.style.height=height+'px';if(carrier)carrier.style.height=height+'px'}}
function t396_addText(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addText');var fieldsString='top,left,width,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addImage(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addImage');var fieldsString='img,width,filewidth,fileheight,top,left,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var images=element.querySelectorAll('img');Array.prototype.forEach.call(images,function(img){img.addEventListener('load',function(){t396_elem__renderViewOneField(element,'top');if(img.src){setTimeout(function(){t396_elem__renderViewOneField(element,'top')},2000)}});if(img.complete){t396_elem__renderViewOneField(element,'top');if(img.src){setTimeout(function(){t396_elem__renderViewOneField(element,'top')},2000)}}
img.addEventListener('tuwidget_done',function(){t396_elem__renderViewOneField(element,'top')})})}
function t396_addShape(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addShape');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addButton(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addButton');var fieldsString='top,left,width,height,container,axisx,axisy,caption,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);return(element)}
function t396_addVideo(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addVideo');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var videoEl=element.querySelector('.tn-atom__videoiframe');var atom=element.querySelector('.tn-atom');if(atom)atom.style.backgroundColor='#000';var videoCover=atom?atom.getAttribute('data-atom-video-has-cover'):'';if(!videoCover)videoCover='';if(videoCover==='y'&&atom){atom.addEventListener('click',function(){var iframe=videoEl?videoEl.querySelector('iframe'):null;var dataOriginal=iframe?iframe.getAttribute('data-original'):'';if(iframe)iframe.setAttribute('src',dataOriginal);atom.style.backgroundImage='none';var playBtn=atom.querySelector('.tn-atom__video-play-link');if(playBtn)playBtn.style.display='none'})}
var allRecords=document.getElementById('allrecords');var autoplay=t396_elem__getFieldValue(element,'autoplay');var showinfo=t396_elem__getFieldValue(element,'showinfo');var loop=t396_elem__getFieldValue(element,'loop');var mute=t396_elem__getFieldValue(element,'mute');var startSec=t396_elem__getFieldValue(element,'startsec');var endSec=t396_elem__getFieldValue(element,'endsec');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var url='';var script=document.createElement('script');script.textContent='lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});';var youtubeID=videoEl?videoEl.getAttribute('data-youtubeid'):'';if(youtubeID){url='//youtube.com/embed/';url+=youtubeID+'?rel=0&fmt=18&html5=1';url+='&showinfo='+(showinfo==='y'?'1':'0');if(loop==='y'){url+='&loop=1&playlist='+youtubeID}
if(startSec>0){url+='&start='+startSec}
if(endSec>0){url+='&end='+endSec}
if(mute==='y'){url+='&mute=1'}
if(videoCover==='y'){url+='&autoplay=1';var instFlag='y';var iframeClass='';if(autoplay==='y'&&mute==='y'&&window.lazy==='y'){instFlag='lazy';iframeClass=' class="t-iframe"'}
videoEl.innerHTML='<iframe id="youtubeiframe"'+iframeClass+' width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="'+instFlag+'"></iframe>';if(autoplay==='y'&&mute==='y'&&window.lazy==='y'){element.insertAdjacentElement('beforeend',script)}
if(autoplay==='y'&&mute==='y'){atom.click()}}else{if(tildaMode!=='edit'&&autoplay==='y'){url+='&autoplay=1'}
if(window.lazy==='y'){videoEl.innerHTML='<iframe id="youtubeiframe" class="t-iframe" width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="lazy"></iframe>';element.insertAdjacentElement('beforeend',script)}else{videoEl.innerHTML='<iframe id="youtubeiframe" width="100%" height="100%" src="'+url+'" frameborder="0" allowfullscreen data-flag-inst="y"></iframe>'}}}
var vimeoID=videoEl?videoEl.getAttribute('data-vimeoid'):'';if(vimeoID){url='//player.vimeo.com/video/';url+=vimeoID+'?color=ffffff&badge=0';if(showinfo==='y'){url+='&title=1&byline=1&portrait=1'}else{url+='&title=0&byline=0&portrait=0'}
if(loop==='y'){url+='&loop=1'}
if(mute==='y'){url+='&muted=1'}
if(videoCover==='y'){url+='&autoplay=1';videoEl.innerHTML='<iframe data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'}else{if(tildaMode!=='edit'&&autoplay==='y'){url+='&autoplay=1'}
if(window.lazy==='y'){videoEl.innerHTML='<iframe class="t-iframe" data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';element.insertAdjacentElement('beforeend',script)}else{videoEl.innerHTML='<iframe src="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'}}}}
function t396_addHtml(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addHtml');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addTooltip(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addTooltip');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits,tipposition';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var tooltip=element.querySelector('.tn-atom__pin');var tooltipContent=element.querySelector('.tn-atom__tip');var tooltipOpenTrigger=element.getAttribute('data-field-tipopen-value');if(window.isMobile||tooltipOpenTrigger==='click'){t396_setUpTooltip_mobile(element,tooltip,tooltipContent)}else{t396_setUpTooltip_desktop(element,tooltip,tooltipContent)}
setTimeout(function(){var atomImages=document.querySelectorAll('.tn-atom__tip-img');Array.prototype.forEach.call(atomImages,function(img){var imgOriginal=img.getAttribute('data-tipimg-original');if(imgOriginal)img.src=imgOriginal})},3000)}
function t396_addForm(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addForm');var fieldsString='width,top,left,';fieldsString+='inputs,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addGallery(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addForm');var fieldsString='width,height,top,left,';fieldsString+='imgs,container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_elem__setFieldValue(element,prop,val,flag_render,flag_updateui,resolution){element=t396_getEl(element);if(!element)return;if(!resolution)resolution=window.tn.curResolution;if(+resolution<1200&&prop!=='zindex'){element.setAttribute('data-field-'+prop+'-res-'+resolution+'-value',val)}else{element.setAttribute('data-field-'+prop+'-value',val)}
if(flag_render==='render')elem__renderViewOneField(element,prop);if(flag_updateui==='updateui')panelSettings__updateUi(element,prop,val)}
function t396_elem__getFieldValue(element,prop){element=t396_getEl(element);if(!element)return;var resolution=window.tn.curResolution;var breakpoints=[1200,960,640,480,320];var dataField;breakpoints.forEach(function(breakpoint,i){if(i===0&&+resolution>=breakpoint){dataField=element.getAttribute('data-field-'+prop+'-value')}
if(i>0&&+resolution===breakpoint){dataField=element.getAttribute('data-field-'+prop+'-res-'+breakpoint+'-value');if(i>1&&!dataField){var slicedBreakpoints=breakpoints.slice(1,i);for(var n=slicedBreakpoints.length-1;n>=0;n--){dataField=element.getAttribute('data-field-'+prop+'-res-'+slicedBreakpoints[n]+'-value');if(dataField)break}}
if(!dataField)dataField=element.getAttribute('data-field-'+prop+'-value')}});return dataField?dataField:''}
function t396_elem__renderView(element){element=t396_getEl(element);tn_console('func: elem__renderView');var fields=element?element.getAttribute('data-fields'):'';if(!fields)return!1;fields=fields.split(',');fields.forEach(function(field){t396_elem__renderViewOneField(element,field)})}
function t396_elem__renderViewOneField(element,field){element=t396_getEl(element);if(!element)return;var value=t396_elem__getFieldValue(element,field);var elementType;var borderWidth;var borderStyle;var currentValue;var slidesMain;var slidesImg;switch(field){case 'left':value=t396_elem__convertPosition__Local__toAbsolute(element,field,value);element.style.left=parseFloat(value).toFixed(1)+'px';break;case 'top':value=t396_elem__convertPosition__Local__toAbsolute(element,field,value);element.style.top=parseFloat(value).toFixed(1)+'px';break;case 'width':value=t396_elem__getWidth(element,value);element.style.width=parseFloat(value).toFixed(1)+'px';elementType=element.getAttribute('data-elem-type');switch(elementType){case 'tooltip':var pinSvgIcon=element.querySelectorAll('.tn-atom__pin-icon');Array.prototype.forEach.call(pinSvgIcon,function(pin){var pinSize=parseFloat(value).toFixed(1)+'px';pin.style.width=pinSize;pin.style.height=pinSize});element.style.height=parseInt(value).toFixed(1)+'px';break;case 'gallery':borderWidth=t396_elem__getFieldValue(element,'borderwidth');borderStyle=t396_elem__getFieldValue(element,'borderstyle');if(!borderStyle||!borderWidth||borderStyle==='none'){borderWidth=0}
value-=borderWidth*2;currentValue=parseFloat(value).toFixed(1)+'px';slidesMain=element.querySelector('.t-slds__main');slidesImg=element.querySelectorAll('.tn-atom__slds-img');element.style.width=currentValue;if(slidesMain)slidesMain.style.width=currentValue;Array.prototype.forEach.call(slidesImg,function(img){img.style.width=currentValue});break}
break;case 'height':elementType=element.getAttribute('data-elem-type');if(elementType==='tooltip')return;value=t396_elem__getHeight(element,value);element.style.height=parseFloat(value).toFixed(1)+'px';if(elementType==='gallery'){borderWidth=t396_elem__getFieldValue(element,'borderwidth');borderStyle=t396_elem__getFieldValue(element,'borderstyle');if(!borderStyle||!borderWidth||borderStyle==='none'){borderWidth=0}
value-=borderWidth*2;currentValue=parseFloat(value).toFixed(1)+'px';slidesMain=element.querySelector('.t-slds__main');slidesImg=element.querySelectorAll('.tn-atom__slds-img');element.style.height=currentValue;if(slidesMain)slidesMain.style.height=currentValue;Array.prototype.forEach.call(slidesImg,function(img){img.style.height=currentValue})}
break;case 'container':t396_elem__renderViewOneField(element,'left');t396_elem__renderViewOneField(element,'top');break;case 'inputs':var textArea=element.querySelector('.tn-atom__inputs-textarea');value=textArea?textArea.value:'';try{t_zeroForms__renderForm($(element),value)}catch(err){}
break}
if(field==='width'||field==='height'||field==='fontsize'||field==='fontfamily'||field==='letterspacing'||field==='fontweight'||field==='img'){t396_elem__renderViewOneField(element,'left');t396_elem__renderViewOneField(element,'top')}}
function t396_elem__convertPosition__Local__toAbsolute(element,field,value){element=t396_getEl(element);if(!element)return;var artBoard=element.closest('.t396__artboard');var verticalAlignValue=t396_ab__getFieldValue(artBoard,'valign');var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var isTildaModeEdit=tildaMode==='edit';var isOnlyScalable=t396_isOnlyScalableBrowser();var isScaledElement=!isTildaModeEdit&&isScaled&&isOnlyScalable;var isZoomedElement=!isTildaModeEdit&&isScaled&&!isOnlyScalable;var valueAxisY=t396_elem__getFieldValue(element,'axisy');var valueAxisX=t396_elem__getFieldValue(element,'axisx');var container=t396_elem__getFieldValue(element,'container');value=parseInt(value);var elementContainer;var offsetLeft;var offsetTop;var elementWidth;var elementContainerWidth;var elementHeight;var elementContainerHeight;switch(field){case 'left':elementContainer=container==='grid'?'grid':'window';offsetLeft=container==='grid'?window.tn.grid_offset_left:0;elementContainerWidth=container==='grid'?window.tn.grid_width:window.tn.window_width;var elementLeftUnits=t396_elem__getFieldValue(element,'leftunits');if(elementLeftUnits==='%'){value=t396_roundFloat(elementContainerWidth*value/100)}
if(!isTildaModeEdit&&isScaled){if(container==='grid'&&isOnlyScalable)value=value*window.tn_scale_factor}else{value=offsetLeft+value}
if(valueAxisX==='center'){elementWidth=t396_elem__getWidth(element);if(isScaledElement&&elementContainer!=='window'){elementContainerWidth*=window.tn_scale_factor;elementWidth*=window.tn_scale_factor}
value=elementContainerWidth/2-elementWidth/2+value}
if(valueAxisX==='right'){elementWidth=t396_elem__getWidth(element);if(isScaledElement&&elementContainer!=='window'){elementContainerWidth*=window.tn_scale_factor;elementWidth*=window.tn_scale_factor}
value=elementContainerWidth-elementWidth+value}
if(isScaledElement&&elementContainer!=='window'){elementWidth=t396_elem__getWidth(element);value=value+(elementWidth*window.tn_scale_factor-elementWidth)/2}
break;case 'top':var artBoardParent=element.parentNode;var proxyMinOffsetTop=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-min-offset-top'):'0';var proxyMinHeight=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-min-height'):'0';var proxyMaxHeight=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-max-height'):'0';var getElementHeight=function(element){var height=t396_elem__getHeight(element);if(element&&element.getAttribute('data-elem-type')==='image'){var width=t396_elem__getWidth(element);var fileWidth=t396_elem__getFieldValue(element,'filewidth');var fileHeight=t396_elem__getFieldValue(element,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);height=width/ratio}}
return height};elementContainer=container==='grid'?'grid':'window';offsetTop=container==='grid'?parseFloat(proxyMinOffsetTop):0;elementContainerHeight=container==='grid'?parseFloat(proxyMinHeight):parseFloat(proxyMaxHeight);var elTopUnits=t396_elem__getFieldValue(element,'topunits');if(elTopUnits==='%'){value=(elementContainerHeight*(value/100))}
if(isScaledElement&&elementContainer!=='window'){value*=window.tn_scale_factor}
if(isZoomedElement&&elementContainer!=='window'){offsetTop=verticalAlignValue==='stretch'?0:(offsetTop/window.tn_scale_factor)}
value=offsetTop+value;var artBoardHeightVH=t396_ab__getFieldValue(artBoardParent,'height_vh');var artBoardMinHeight=t396_ab__getFieldValue(artBoardParent,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoardParent);if(isScaled&&!isTildaModeEdit&&artBoardHeightVH){var scaledMinHeight=parseInt(artBoardMinHeight,10)*window.tn_scale_factor}
if(valueAxisY==='center'){elementHeight=getElementHeight(element);if(isScaledElement&&elementContainer!=='window'){if(verticalAlignValue!=='stretch'){elementContainerHeight=elementContainerHeight*window.tn_scale_factor}else{if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}}
elementHeight*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&elementContainer!=='window'&&verticalAlignValue==='stretch'){if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}
elementContainerHeight=elementContainerHeight/window.tn_scale_factor}
value=elementContainerHeight/2-elementHeight/2+value}
if(valueAxisY==='bottom'){elementHeight=getElementHeight(element);if(isScaledElement&&elementContainer!=='window'){if(verticalAlignValue!=='stretch'){elementContainerHeight=elementContainerHeight*window.tn_scale_factor}else{if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}}
elementHeight*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&elementContainer!=='window'&&verticalAlignValue==='stretch'){if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}
elementContainerHeight=elementContainerHeight/window.tn_scale_factor}
value=elementContainerHeight-elementHeight+value}
if(isScaledElement&&elementContainer!=='window'){elementHeight=getElementHeight(element);value=value+(elementHeight*window.tn_scale_factor-elementHeight)/2}
break}
return value}
function t396_ab__setFieldValue(artBoard,prop,val,resolution){if(!resolution)resolution=window.tn.curResolution;if(resolution<1200){if(artBoard)artBoard.setAttribute('data-artboard-'+prop+'-res-'+resolution,val)}else{if(artBoard)artBoard.setAttribute('data-artboard-'+prop,val)}}
function t396_ab__getFieldValue(artBoard,prop){if(!artBoard)return;var resolution=window.tn.curResolution;var breakpoints=[1200,960,640,480,320];var dataField;breakpoints.forEach(function(breakpoint,i){if(i===0&&+resolution>=breakpoint){dataField=artBoard.getAttribute('data-artboard-'+prop)}
if(i>0&&+resolution===breakpoint){dataField=artBoard.getAttribute('data-artboard-'+prop+'-res-'+breakpoint);if(i>1&&!dataField){var slicedBreakpoints=breakpoints.slice(1,i);for(var n=slicedBreakpoints.length-1;n>=0;n--){dataField=artBoard.getAttribute('data-artboard-'+prop+'-res-'+slicedBreakpoints[n]);if(dataField)break}}
if(!dataField)dataField=artBoard.getAttribute('data-artboard-'+prop)}});return dataField?dataField:''}
function t396_ab__renderViewOneField(artBoard,field){t396_ab__getFieldValue(artBoard,field)}
function t396_allelems__renderView(artBoard){if(!artBoard)return!1;tn_console('func: allelems__renderView: abid:'+artBoard.getAttribute('data-artboard-recid'));var ArtBoardelements=artBoard.querySelectorAll('.tn-elem');Array.prototype.forEach.call(ArtBoardelements,function(element){t396_elem__renderView(element)})}
function t396_ab__filterUpdate(artBoard){var filter=artBoard.querySelector('.t396__filter');if(!filter)return;var filterColorRgb=filter.getAttribute('data-filtercolor-rgb');var filterColorRgb2=filter.getAttribute('data-filtercolor2-rgb');var filterOpacity=filter.getAttribute('data-filteropacity');var filterOpacity2=filter.getAttribute('data-filteropacity2');if(filterColorRgb&&!filterColorRgb2){filter.style.backgroundColor='rgba('+filterColorRgb+','+filterOpacity+')'}else if(!filterColorRgb&&filterColorRgb2){filter.style.backgroundColor='rgba('+filterColorRgb2+','+filterOpacity2+')'}else if(filterColorRgb&&filterColorRgb2){filter.style.background='-webkit-gradient(linear, left top, left bottom, from(rgba('+filterColorRgb+','+filterOpacity+')), to(rgba('+filterColorRgb2+','+filterOpacity2+')) )'}else{filter.style.backgroundColor='transparent'}}
function t396_ab__getHeight(artBoard,artBoardHeight){if(!artBoardHeight)artBoardHeight=t396_ab__getFieldValue(artBoard,'height');artBoardHeight=parseFloat(artBoardHeight);var artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');if(artBoardHeightVH){artBoardHeightVH=parseFloat(artBoardHeightVH);if(!isNaN(artBoardHeightVH)){var artBoardHeightVHpx=window.tn.window_height*artBoardHeightVH/100;if(artBoardHeight<artBoardHeightVHpx){artBoardHeight=artBoardHeightVHpx}}}
return artBoardHeight}
function t396_hex2rgb(hexStr){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b]}
String.prototype.t396_replaceAll=function(search,replacement){var target=this;return target.replace(new RegExp(search,'g'),replacement)};function t396_elem__getWidth(element,value){element=t396_getEl(element);if(!value)value=t396_elem__getFieldValue(element,'width');value=parseFloat(value);var elWidthUnits=t396_elem__getFieldValue(element,'widthunits');if(elWidthUnits==='%'){var elementContainer=t396_elem__getFieldValue(element,'container');if(elementContainer==='window'){value=window.tn.window_width*value/100}else{value=window.tn.grid_width*value/100}}
return value}
function t396_elem__getHeight(element,value){element=t396_getEl(element);if(!value)value=t396_elem__getFieldValue(element,'height');value=parseFloat(value);var elemType=element.getAttribute('data-elem-type');if(elemType==='shape'||elemType==='video'||elemType==='html'||elemType==='gallery'){var elHeightUnits=t396_elem__getFieldValue(element,'heightunits');if(elHeightUnits==='%'){var artBoard=element.parentNode;var proxyMinHeight=artBoard?artBoard.getAttribute('data-artboard-proxy-min-height'):'0';var proxyMaxHeight=artBoard?artBoard.getAttribute('data-artboard-proxy-max-height'):'0';var artBoardMinHeight=parseFloat(proxyMinHeight);var artBoardMaxHeight=parseFloat(proxyMaxHeight);var elementContainer=t396_elem__getFieldValue(element,'container');if(elementContainer==='window'){value=artBoardMaxHeight*(value/100)}else{value=artBoardMinHeight*(value/100)}}}else if(elemType!=='button'){value=element.clientHeight}
return value}
function t396_roundFloat(n){n=Math.round(n*100)/100;return(n)}
function tn_console(str){if(+(window.tn_comments)===1)console.log(str)}
function t396_setUpTooltip_desktop(element,tooltip,tooltipContent){element=t396_getEl(element);var timer;if(tooltip){tooltip.addEventListener('mouseover',function(){var visibleEls=document.querySelectorAll('.tn-atom__tip_visible');Array.prototype.forEach.call(visibleEls,function(visibleEl){var curTipEl=visibleEl.closest('.t396__elem');var cirTipElID=curTipEl?curTipEl.getAttribute('data-elem-id'):'';if(cirTipElID!==element.getAttribute('data-elem-id')){t396_hideTooltip(curTipEl,visibleEl)}});clearTimeout(timer);if(tooltipContent&&tooltipContent.style.display==='block')return;t396_showTooltip(element,tooltipContent)});tooltip.addEventListener('mouseout',function(){timer=setTimeout(function(){t396_hideTooltip(element,tooltipContent)},300)})}}
function t396_setUpTooltip_mobile(element,tooltip,tooltipContent){element=t396_getEl(element);if(tooltip){tooltip.addEventListener('click',function(){if(tooltipContent&&tooltipContent.style.display==='block'&&tooltip.classList.contains('tn-atom__pin')){t396_hideTooltip(element,tooltipContent)}else{t396_showTooltip(element,tooltipContent)}})}
var elementID=element.getAttribute('data-elem-id');document.addEventListener('click',function(e){if(e.target.closest('.tn-atom__pin')){var zbEl=e.target.closest('.t396__elem');var clickedPinId=zbEl?zbEl.getAttribute('data-elem-id'):'';if(clickedPinId===elementID)return}
t396_hideTooltip(element,tooltipContent)})}
function t396_hideTooltip(element,tooltipContent){if(tooltipContent)tooltipContent.style.display='';if(tooltipContent)tooltipContent.style.left='';if(tooltipContent)tooltipContent.style.transform='';if(tooltipContent)tooltipContent.style.right='';if(tooltipContent)tooltipContent.classList.remove('tn-atom__tip_visible');if(element)element.style.zIndex=''}
function t396_showTooltip(element,tooltipContent){element=t396_getEl(element);var pos=element.getAttribute('data-field-tipposition-value');if(!pos)pos='top';var elSize=element.clientHeight;var elTop=element.getBoundingClientRect().top+window.pageYOffset;var elBottom=elTop+elSize;var elLeft=element.getBoundingClientRect().left+window.pageXOffset;var elRight=elLeft+elSize;var winTop=window.pageYOffset;var winWidth=document.documentElement.clientWidth;var winBottom=winTop+document.documentElement.clientHeight;if(tooltipContent)tooltipContent.style.display='block';if(tooltipContent)tooltipContent.style.zIndex='-9999';if(tooltipContent)tooltipContent.style.transform='translateX(-10000px)';var tipElHeight=tooltipContent?tooltipContent.offsetHeight:0;var tipElWidth=tooltipContent?tooltipContent.offsetWidth:0;if(tooltipContent)tooltipContent.style.display='';if(tooltipContent)tooltipContent.style.zIndex='';if(tooltipContent)tooltipContent.style.transform='';var padding=15;var tipElRight;var tipElLeft;var tipElTop;var tipElBottom;if(pos==='right'||pos==='left'){tipElRight=elRight+padding+tipElWidth;tipElLeft=elLeft-padding-tipElWidth;if((pos==='right'&&tipElRight>winWidth)||(pos==='left'&&tipElLeft<0)){pos='top'}}
if(pos==='top'||pos==='bottom'){tipElRight=elRight+(tipElWidth/2-elSize/2);tipElLeft=elLeft-(tipElWidth/2-elSize/2);if(tipElRight>winWidth){var rightOffset=-(winWidth-elRight-padding);if(tooltipContent)tooltipContent.style.left='auto';if(tooltipContent)tooltipContent.style.transform='none';if(tooltipContent)tooltipContent.style.right=rightOffset+'px'}
if(tipElLeft<0){var leftOffset=-(elLeft-padding);if(tooltipContent)tooltipContent.style.left=leftOffset+'px';if(tooltipContent)tooltipContent.style.transform='none'}}
if(pos==='top'){tipElTop=elTop-padding-tipElHeight;tipElBottom=elBottom+padding+tipElHeight;if(winBottom>tipElBottom&&winTop>tipElTop){pos='bottom'}}
if(pos==='bottom'){tipElTop=elTop-padding-tipElHeight;tipElBottom=elBottom+padding+tipElHeight;if(winBottom<tipElBottom&&winTop<tipElTop){pos='top'}}
if(tooltipContent)tooltipContent.setAttribute('data-tip-pos',pos);if(tooltipContent)tooltipContent.style.display='block';if(tooltipContent)tooltipContent.classList.add('tn-atom__tip_visible');if(element)element.style.zIndex='1000'}
function t396_hex2rgba(hexStr,opacity){if(!hexStr)return!1;var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b,parseFloat(opacity)]}
function t396_removeElementFromDOM(el){el=t396_getEl(el);if(el&&el.parentNode){el.parentNode.removeChild(el)}}
function t396_getEl(el){if(el instanceof jQuery){return el.length?el.get(0):null}else{return el}}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}
function t397_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var tildaLazyMode=allRecords?allRecords.getAttribute('data-tilda-lazy'):'';var tabs=rec?rec.querySelectorAll('.t397__tab'):[];if(tildaMode!=='edit'&&tildaMode!=='preview'){t397_scrollToTabs(recid)}
Array.prototype.forEach.call(tabs,function(tab,i){tab.addEventListener('click',function(e){var targetTab=e.target.closest('.t397__tab');if(targetTab&&targetTab.classList.contains('t397__tab_active')&&!e.isTrusted)return;var activeTab=rec.querySelector('.t397__tab_active');if(activeTab)activeTab.classList.remove('t397__tab_active');targetTab.classList.add('t397__tab_active');t397_removeUrl();var tabNumber=i+1;if(tildaMode!=='edit'&&tildaMode!=='preview'&&tabNumber&&typeof history.replaceState!=='undefined'){try{window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}catch(err){}}
t397_alltabs_updateContent(recid);t397_updateSelect(recid);var hookBlocks=targetTab.getAttribute('data-tab-rec-ids').split(',');var event=document.createEvent('Event');event.initEvent('displayChanged',!0,!0);hookBlocks.forEach(function(curRecid){var currentRec=document.getElementById('rec'+curRecid);if(!currentRec)return;var currentRecChildren=currentRec.querySelectorAll('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t448, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t569, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t902, .t912, .t923, .t937, .t959, .t979, .t982, .t983, .t989, .t994');Array.prototype.forEach.call(currentRecChildren,function(child){child.dispatchEvent(event)});var displayChangedBlock=currentRec.querySelector('[data-display-changed="true"]');if(displayChangedBlock)displayChangedBlock.dispatchEvent(event)});var galaxyEffectBlocks=document.querySelectorAll('.t826');Array.prototype.forEach.call(galaxyEffectBlocks,function(galaxyEffectBlock){galaxyEffectBlock.dispatchEvent(event)});t397_startUpdateLazyLoad(targetTab);if(window.lazy==='y'||tildaLazyMode==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});if(tabs.length){t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid);var bgColor=rec?rec.style.backgroundColor:'#ffffff';var bgColorTargets=rec.querySelectorAll('.t397__select, .t397__firefoxfix');Array.prototype.forEach.call(bgColorTargets,function(target){target.style.background=bgColor})}
document.addEventListener('click',function(e){if(e.target.closest('[href*="#!/tab/'+recid+'"]')){var currentLink=e.target.closest('[href*="#!/tab/'+recid+'"]');var hash=currentLink.hash;t397_scrollToTabs(recid,hash)}})}
function t397_alltabs_updateContent(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var tabs=Array.prototype.slice.call(rec.querySelectorAll('.t397__tab:not(.t397__tab_active)'));var activeTab=rec.querySelector('.t397__tab_active');var select=rec.querySelector('.t397__select');if(!activeTab)return;var hookBlocks=activeTab.getAttribute('data-tab-rec-ids').split(',');var noActive=[];Array.prototype.forEach.call(tabs,function(tab){if(tab!==activeTab){var noActiveHooks=tab.getAttribute('data-tab-rec-ids').split(',');noActiveHooks.forEach(function(hook){if(noActive.indexOf(hook)===-1&&hookBlocks.indexOf(hook)===-1)noActive.push(hook)})}});if(t397_checkVisibillityEl(activeTab)||t397_checkVisibillityEl(select)){hookBlocks.forEach(function(hook){if(!hook)return;var hookEl=document.getElementById('rec'+hook);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl)hookEl.classList.remove('t397__off');if(hookEl)hookEl.style.opacity='';t397_updateTabsByHook(hookElRecordType,hookEl,hook,recid)})}else{hookBlocks.forEach(function(hook){var hookEl=document.getElementById('rec'+hook);if(hookEl)hookEl.setAttribute('data-animationappear','off');if(hookEl)hookEl.classList.add('t397__off')})}
noActive.forEach(function(noActiveID){if(!noActiveID)return;var hookEl=document.getElementById('rec'+noActiveID);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl)hookEl.setAttribute('data-connect-with-tab','yes');if(hookEl)hookEl.setAttribute('data-animationappear','off');if(hookEl)hookEl.classList.add('t397__off');t397_updateTabsByHook(hookElRecordType,hookEl,noActiveID,recid)});var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(scrollHeight-window.innerHeight<window.pageYOffset){window.scrollTo(0,0)}}
function t397_updateTabsByHook(hookElRecordType,hookEl,currentID,recid){var hookElTab;switch(hookElRecordType){case '395':if(window.t395_alltabs_updateContent&&window.t395_updateSelect&&recid!==currentID){window.t395_alltabs_updateContent(currentID);window.t395_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t395__tab'):null;if(hookElTab)hookElTab.click()}
break;case '397':if(recid!==currentID){t397_alltabs_updateContent(currentID);t397_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t397__tab'):null;if(hookElTab)hookElTab.click()}
break}}
function t397_checkVisibillityEl(el){return!!(el&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length))}
function t397_updateContentBySelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var select=rec.querySelector('.t397__select');if(select){select.addEventListener('change',function(){var currentValue=select.value;var tabIndex=rec.querySelector('.t397__tab[data-tab-rec-ids=\''+currentValue+'\']');if(tabIndex)tabIndex.click()})}}
function t397_updateSelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var activeTab=rec.querySelector('.t397__tab_active');var currentTabHooks=activeTab?activeTab.getAttribute('data-tab-rec-ids'):'';var select=rec.querySelector('.t397__select');if(select)select.value=currentTabHooks}
function t397_startUpdateLazyLoad(el){var hookBlocks=el?el.getAttribute('data-tab-rec-ids').split(','):[];hookBlocks.forEach(function(hook){var rec=document.getElementById('rec'+hook);if(!rec)return;var videos=rec.querySelectorAll('.t-video-lazyload');if(videos.length){t397_updateVideoLazyLoad(videos)}})}
function t397_updateVideoLazyLoad(videos){setTimeout(function(){Array.prototype.forEach.call(videos,function(video){if(!video.classList.contains('t-video__isload')){var heightAttribute=video.getAttribute('data-videolazy-height');var height=heightAttribute?heightAttribute:'100%';if(height.indexOf('vh')!==-1)height='100%';var videoID=video.getAttribute('data-videolazy-id');videoID=videoID?videoID.trim():'';var blockID=video.getAttribute('data-blocklazy-id');var twoIdAttr=video.getAttribute('data-videolazy-two-id');var videoTwoID=twoIdAttr?'_'+twoIdAttr+'_':'';if(video.getAttribute('data-videolazy-type')==='youtube'){var oldIframe=video.querySelector('iframe');if(oldIframe&&oldIframe.parentNode)oldIframe.parentNode.removeChild(oldIframe);var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+videoTwoID+blockID;iframe.width='100%';iframe.height=height;iframe.src='https://www.youtube.com/embed/'+videoID+'?rel=0&fmt=18&html5=1&showinfo=0';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');video.insertAdjacentElement('beforeend',iframe)}}
video.classList.add('t-video__isload')})},2)}
function t397_scrollToTabs(recid,hash){var rec=document.getElementById('rec'+recid);var curUrl=hash||window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');if(tabIndexNumber===-1)return!1;var tabIndexNumberStart=curUrl.indexOf('tab/');var firstOptionSelect=rec?rec.querySelector('.t397__wrapper_mobile .t397__select option'):null;if(firstOptionSelect)firstOptionSelect.selected=!1;var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(tabRec!==recid)return!1;var tabBlock=rec?rec.querySelector('.t397'):null;var tabNumber=parseInt(curUrl.slice(tabIndexNumberStart+4+recid.length+1),10);var tabs=rec.querySelectorAll('.t397__tab');Array.prototype.forEach.call(tabs,function(tab,i){if(i===tabNumber-1){tab.click();tab.classList.add('t397__tab_active')}else{tab.classList.remove('t397__tab_active')}});var tabsMob=rec.querySelectorAll('.t397__wrapper_mobile .t397__select option');var activeTabMob=tabsMob.length?tabsMob[tabNumber-1]:null;if(activeTabMob)activeTabMob.selected=!0;var targetOffset=tabBlock.getBoundingClientRect().top+window.pageYOffset;var target=window.innerWidth>960?targetOffset-200:targetOffset-100;if(target<0)target=0;t397_scrollToEl(target)}
function t397_scrollToEl(elTopPos){if(elTopPos===window.pageYOffset)return!1;var duration=300;var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=10*(elTopPos||window.pageYOffset)/duration;var timer=setInterval(function(){if(cashedDiff>elTopPos){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>elTopPos&&window.pageYOffset<=elTopPos||cashedDiff<=elTopPos&&window.pageYOffset>=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10);var timer2=setTimeout(function(){clearInterval(timer);document.body.removeAttribute('data-scrollable');clearTimeout(timer2)},duration*2)}
function t397_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(indexToRemove===-1){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!==-1){if(typeof history.replaceState!='undefined'){try{window.history.replaceState('','',curUrl)}catch(err){}}}}
function t400_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t400');if(!container)return;var button=rec.querySelector('.t400__submit');var hideBackText=button.getAttribute('data-hide-back-text');var showMoreText=button.textContent;button.addEventListener('click',function(){if(hideBackText&&button.classList.contains('t400__submit_hide-back')){t400_alltabs_updateContent(recId);button.classList.remove('t400__submit_hide-back');if(button.classList.contains('t400__submit-overflowed')){button.innerHTML='<span class="t400__text">'+showMoreText+'</span>'}else{button.innerHTML=showMoreText}
var zeroBlocks=document.querySelectorAll('.t396');for(var i=0;i<zeroBlocks.length;i++){t400__triggerEvent(zeroBlocks[i],'displayChanged')}
return}
var recIds=button.getAttribute('data-hidden-rec-ids').split(',');for(var i=0;i<recIds.length;i++){var recShowBlock=document.getElementById('rec'+recIds[i]);if(recShowBlock){recShowBlock.classList.remove('t400__off');recShowBlock.style.opacity='';var videos=recShowBlock.querySelectorAll('.t-video-lazyload');if(videos.length>0){var video=videos[0];if(video.closest('.t121')||video.closest('.t223')||video.closest('.t230')||video.closest('.t368')){t400_updateVideoLazyLoad(videos)}}
var selectors=recShowBlock.querySelectorAll('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t527, .t531, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t899, .t902, .t905, .t912, .t923, .t937, .t958, .t959, .t979, .t982, .t983, .t989, .t994, .t1000, .t1003');for(var j=0;j<selectors.length;j++){t400__triggerEvent(selectors[j],'displayChanged')}}}
if(hideBackText){button.classList.add('t400__submit_hide-back');if(button.classList.contains('t400__submit-overflowed')){button.innerHTML='<span class="t400__text">'+hideBackText+'</span>'}else{button.innerHTML=hideBackText}}else{rec.classList.add('t400__off');rec.style.display='none'}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});t400_alltabs_updateContent(recId);t400_checkSize(recId);if(typeof jQuery!=='undefined'){$(container).bind('displayChanged',function(){t400_checkSize(recId)})}else{container.addEventListener('displayChanged',function(){t400_checkSize(recId)})}}
function t400_alltabs_updateContent(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t400__submit');if(!button)return;var recIds=button.getAttribute('data-hidden-rec-ids').split(',');for(var i=0;i<recIds.length;i++){var recHideBlock=document.getElementById('rec'+recIds[i]);if(!recHideBlock)return;recHideBlock.setAttribute('data-animationappear','off');recHideBlock.setAttribute('data-connect-with-tab','yes');recHideBlock.classList.add('t400__off')}}
function t400_checkSize(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t400__submit');if(!button)return;var buttonStyle=getComputedStyle(button,null);var buttonPaddingTop=parseInt(buttonStyle.paddingTop)||0;var buttonPaddingBottom=parseInt(buttonStyle.paddingBottom)||0;var buttonHeight=button.clientHeight-(buttonPaddingTop+buttonPaddingBottom);var buttonScrollHeight=button.scrollHeight;if(buttonHeight<buttonScrollHeight){var buttonText=button.textContent;button.classList.add('t400__submit-overflowed');button.innerHTML='<span class="t400__text">'+buttonText+'</span>'}}
function t400_updateVideoLazyLoad(videos){setTimeout(function(){for(var i=0;i<videos.length;i++){var video=videos[i];var videoHeight=video.getAttribute('data-videolazy-height')||'100%';if(videoHeight.indexOf('vh')!==-1){videoHeight='100%'}
var videoId=video.getAttribute('data-videolazy-id').trim();var blockId=video.getAttribute('data-blocklazy-id')||'';var videoTwoId=video.getAttribute('data-videolazy-two-id')||'';if(videoTwoId)videoTwoId='_'+videoTwoId+'_';if(video.getAttribute('data-videolazy-type')==='youtube'){var iframes=video.querySelectorAll('iframe');for(var j=0;j<iframes.length;j++){var oldFrame=iframes[j];if(oldFrame&&oldFrame.parentNode)oldFrame.parentNode.removeChild(oldFrame)}
var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+videoTwoId+blockId;iframe.width='100%';iframe.height=videoHeight;iframe.src='//www.youtube.com/embed/'+videoId+'?rel=0&fmt=18&html5=1&showinfo=0';iframe.setAttribute('frameborder','0');iframe.setAttribute('allowfullscreen','');video.insertBefore(iframe,video.firstChild)}}})}
function t400__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t449_appearMenu(recId){if(window.innerWidth>980){var recs=document.querySelectorAll('.t449');var scrollTop=window.pageYOffset;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);for(var i=0;i<recs.length;i++){var rec=recs[i];var appearOffset=rec.getAttribute('data-appearoffset');var hideOffset=rec.getAttribute('data-hideoffset');if(appearOffset){if(appearOffset.indexOf('vh')>-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);if(scrollTop>=appearOffset){if(rec.classList.contains('t449__beforeready')){rec.classList.remove('t449__beforeready')}}else{rec.classList.add('t449__beforeready')}}
if(hideOffset){if(hideOffset.indexOf('vh')>-1){hideOffset=Math.floor((window.innerHeight*(parseInt(hideOffset)/100)))}
hideOffset=parseInt(hideOffset,10);if(scrollTop+window.innerHeight>=documentHeight-hideOffset){if(!rec.classList.contains('t449__beforeready')){rec.classList.add('t449__beforeready')}}else if(appearOffset){if(scrollTop>=appearOffset){rec.classList.remove('t449__beforeready')}}else{rec.classList.remove('t449__beforeready')}}}}}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');var menuLinks=rec.querySelectorAll('.t-menu__link-item');var menuLinksEls=rec.querySelectorAll('.t978__menu-link');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});Array.prototype.forEach.call(menuLinks,function(link){if(link.classList.contains('t966__tm-link')){link.addEventListener('click',function(){setTimeout(function(){t450_checkSize(recid)},300)})}
if(link.classList.contains('t978__tm-link')){link.addEventListener('click',function(){Array.prototype.forEach.call(menuLinksEls,function(element){element.addEventListener('click',function(){t450_checkSize(recid)})})})}});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;if(topContainerHeight+rightContainerHeight>window.innerHeight){menu.classList.add('t450__overflowed');if(container)container.style.height='auto'}else{menu.classList.remove('t450__overflowed');if(container)container.style.height=''}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__burger_container'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t602_init(recid){$(window).on('scroll',t_throttle(function(){t602_setProgressBarWidth(recid)},100))}
function t602_setProgressBarWidth(recid){var t602_windowScrollTop=$(window).scrollTop(),t602_docHeight=$(document).height(),t602_winHeight=$(window).height();t602_scrollPercent=(t602_windowScrollTop/(t602_docHeight-t602_winHeight))*100;$(".t602__indicator").css('width',t602_scrollPercent+'%')}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var playBtns=rec.querySelectorAll('.t670__play');Array.prototype.forEach.call(playBtns,function(play){play.addEventListener('click',function(){var videoType=play.getAttribute('data-slider-video-type');var url;var nextEl;var prevEl;var iframe;var video;var source;switch(videoType){case 'youtube':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;if(nextEl){iframe=document.createElement('iframe');iframe.classList.add('t670__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://www.youtube.com/embed/'+url+'?autoplay=1&enablejsapi=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay');nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',iframe)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break;case 'vimeo':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;if(nextEl){iframe=document.createElement('iframe');iframe.classList.add('t670__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://player.vimeo.com/video/'+id+hash+'&amp;api=1';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay; fullscreen');nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',iframe)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break;case 'mp4':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;if(nextEl){video=document.createElement('video');source=document.createElement('source');video.insertAdjacentElement('beforeend',source);video.classList.add('t670__video');video.controls=!0;source.src=url;nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',video)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break}
if(nextEl)nextEl.style.zIndex='3'})})}
function t670_hide(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var elBody=rec.querySelector('.t670__frame');rec.addEventListener('updateSlider',function(){if(elBody)elBody.innerHTML='';if(elBody)elBody.style.zIndex=''})}
function t670_imageHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var images=rec.querySelectorAll('.t670__separator');Array.prototype.forEach.call(images,function(img){var width=img.getAttribute('data-slider-image-width')||0;var height=img.getAttribute('data-slider-image-height')||0;var ratio=height/width;var padding=ratio*100;img.style.paddingBottom=padding+'%'})}
function t674_init(recid){var el=$("#rec"+recid);el.find('.t674__img-holder').on('load',function(){var delay=0;if($('#allrecords').attr('data-blocks-animationoff')!=='yes'){delay=600}
setTimeout(function(){$('body').addClass('t674__body_with-bg')},delay)}).each(function(){if(this.complete)$(this).trigger('load')})}
function t772_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t772__container_mobile-flex');if(!container)return;var cols=rec.querySelectorAll('.t772__col');container.addEventListener('touchstart',function(){for(var i=0;i<cols.length;i++){var col=cols[i];col.removeEventListener('touchmove',t722_touchEvent);col.addEventListener('touchmove',t722_touchEvent)}})}
function t722_touchEvent(){var allRecords=document.getElementById('allrecords');if(typeof allRecords.getAttribute('data-tilda-mode')==='undefined'){if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}}
function t794_init(recid){var hook=$('#rec'+recid+' .t794').attr('data-tooltip-hook');if(typeof hook==="undefined"||hook===""){return}
var hookLinks=$('a[href="'+hook+'"][data-submenu-disallowed!="yes"]');hookLinks.addClass('t794__tm-link');hookLinks.attr('data-tooltip-menu-id',recid);t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t794_highlight()}
function t794_setUpMenu(recid,hookLinks){var submenu=$('#rec'+recid+' .t794__tooltip-menu');var content=submenu.find('t794__content');if(window.isMobile){t794_setUpMenu_mobile(recid,hookLinks,submenu)}else{t794_setUpMenu_desktop(recid,hookLinks,submenu)}
$(window).bind('scroll',t_throttle(function(){content.hover(function(){},function(){if(submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}})},300));$('.t794__tooltip-menu a[href*="#"]').click(function(){t794_hideSubmenu(submenu);$('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466').trigger('clickedAnchorInTooltipMenu');$('.t794__tooltip-menu a[href*="#"]').removeClass('t-active');$(this).addClass('t-active')})}
function t794_setUpMenu_mobile(recid,hookLinks,submenu){var vIndent=$('#rec'+recid+' .t794').attr('data-tooltip-margin');hookLinks.on('click',function(e){if(submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}else{var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)}
e.preventDefault()});$(document).click(function(e){var isInsideSubmenu=($(e.target).hasClass('t794__tooltip-menu')||$(e.target).parents('.t794__tooltip-menu').length>0);var isAnchor=($(e.target).hasClass('t794__tm-link')||$(e.target).parents('.t794__tm-link').length>0);if(isAnchor){var curAnchor;if($(e.target).hasClass('t794__tm-link')){curAnchor=$(e.target)}else{curAnchor=$(e.target).parents('.t794__tm-link')}
if(curAnchor.attr('data-tooltip-menu-id')!=recid&&submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}}
if(!isInsideSubmenu&&!isAnchor&&submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}})}
function t794_setUpMenu_desktop(recid,hookLinks,submenu){var vIndent=$('#rec'+recid+' .t794').attr('data-tooltip-margin');var timer;hookLinks.add(submenu).on('mouseover',function(){if($(this).hasClass('t794__tooltip-menu')&&!$(this).hasClass('t794__tooltip-menu_show')){return}
clearTimeout(timer);if($(this).hasClass('t794__tooltip-menu')&&submenu.hasClass('t794__tooltip-menu_show')){return}
var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)});hookLinks.add(submenu).on('mouseout',function(){timer=setTimeout(function(){t794_hideSubmenu(submenu)},300)});hookLinks.on('click',function(e){e.preventDefault()})}
function t794_showSubmenu(curAnchor,submenu,vIndent){var submenuHeight=submenu.outerHeight();var submenuWidth=submenu.outerWidth();var anchorHeight=curAnchor.height();var anchorWidth=curAnchor.width();if(curAnchor.hasClass('t-btn')){anchorWidth=curAnchor.outerWidth()}
var winHeight=$(window).height();var winWidth=$(window).width();var scrollTop=$(window).scrollTop();var anchorLeft=curAnchor.offset().left;var anchorTop=window.isFirefox||window.isOpera?curAnchor.offset().top:curAnchor.offset().top*window.tn_scale_factor;submenu.attr('data-pos-fixed','no');var parentMenu=curAnchor.closest('[data-menu="yes"]');var parentZeroMenu=curAnchor.closest('.t396__artboard');if(parentMenu.length&&parentMenu.css('position')==='fixed'){submenu.attr('data-pos-fixed','yes')}
var menuFixed=submenu.attr('data-pos-fixed');var submenuContent=submenu.find('.t794__content');if(typeof vIndent!='undefined'&&vIndent!=''){vIndent=vIndent.replace('px','')*1;vIndent=vIndent+10}
var posy;if(menuFixed=='yes'){posy=(anchorTop-scrollTop)+anchorHeight+vIndent;submenu.css('position','fixed');submenu.removeClass('t794__tooltip-menu_top').addClass('t794__tooltip-menu_bottom');submenuContent.css('max-height','calc(100vh - '+posy+'px)')}else{posy=anchorTop+anchorHeight+vIndent;submenu.css('position','absolute');var topSpace=anchorTop-scrollTop,bottomSpace=winHeight-topSpace;if(posy+submenuHeight>scrollTop+winHeight&&topSpace>bottomSpace){posy=posy-submenuHeight-anchorHeight-vIndent*2;submenu.removeClass('t794__tooltip-menu_bottom').addClass('t794__tooltip-menu_top')}else{submenu.removeClass('t794__tooltip-menu_top').addClass('t794__tooltip-menu_bottom')}}
var posx=anchorLeft;if(parentZeroMenu.hasClass('t396__artboard_scale')&&window.tn_scale_factor){posx=window.isFirefox||window.isOpera?posx:posx*window.tn_scale_factor;anchorWidth=anchorWidth*window.tn_scale_factor}
if(posx+submenuWidth/2<winWidth){posx=posx+(anchorWidth-submenuWidth)/2;if(posx<0){posx=10}}else{posx=winWidth-submenuWidth-10}
submenu.css({'display':'block','left':posx,'top':posy});submenu[0].offsetHeight;submenu.addClass('t794__tooltip-menu_show');curAnchor.addClass('t794__tm-link_active')}
function t794_hideSubmenu(submenu){submenu.css({'display':'','left':'','top':''});submenu.removeClass('t794__tooltip-menu_show');$('.t794__tm-link_active').removeClass('t794__tm-link_active')}
function t794_addArrow(recid,hookLinks){var arrow=$('#rec'+recid+' .t794').attr('data-add-arrow');if(typeof arrow==='undefined'||arrow===''){return}
hookLinks.each(function(i,el){$(el).append('<div class="t794__arrow"></div>')})}
function t794_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$('.t794__list_item a[href="'+url+'"]').addClass('t-active');$('.t794__list_item a[href="'+url+'/"]').addClass('t-active');$('.t794__list_item a[href="'+pathname+'"]').addClass('t-active');$('.t794__list_item a[href="/'+pathname+'"]').addClass('t-active');$('.t794__list_item a[href="'+pathname+'/"]').addClass('t-active');$('.t794__list_item a[href="/'+pathname+'/"]').addClass('t-active');if(hash){$('.t794__list_item a[href="'+hash+'"]').addClass('t-active')}}
function t826_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t826');t826_startAnimation(recid);if(!window.isMobile){window.addEventListener('resize',t_throttle(function(){t826_prepareAnimation(recid)}))}
if(window.isMobile){window.addEventListener('orientationchange',function(){t826_prepareAnimation(recid)})}
if(typeof jQuery!=='undefined'){$('.t826').bind('displayChanged',function(){t826_prepareAnimation(recid)})}else{wrapper.addEventListener('displayChanged',function(){t826_prepareAnimation(recid)})}}
function t826_prepareAnimation(recid){var galaxy=document.querySelector('div:not(.t826__animation) > div[data-galaxy-id="'+recid+'"]');if(galaxy&&galaxy.parentNode!==null){galaxy.parentNode.removeChild(galaxy)}
t826_startAnimation(recid)}
function t826_startAnimation(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t826');if(!wrapper)return;var galaxy=rec.querySelector('.t826__galaxy');if(!galaxy)return;var allRecords=document.querySelector('#allrecords');var recIds=wrapper.getAttribute('data-galaxy-rec-ids');var wholePage=wrapper.getAttribute('data-galaxy-whole-page');var verticalFlip=wrapper.getAttribute('data-galaxy-vflip');var color=wrapper.getAttribute('data-element-color');var opacity=wrapper.getAttribute('data-element-opacity');var options={'color':(!color?'#fff':color),'opacity':(!opacity?1:opacity.replace(/^0?.([0-9])0?$/g,'.$1'))};if(options.color.indexOf('#')!==-1){var color=options.color;if(color[1]===color[2]&&color[3]===color[4]&&color[5]===color[6]){options.color='#'+color[1]+color[3]+color[5]}}
if(verticalFlip==='yes'){galaxy.classList.add('t826__galaxy_flip')}
if(allRecords.getAttribute('data-tilda-mode')==='edit'){var wrapper=rec.querySelector('.t826__demo');wrapper.insertAdjacentElement('beforeend',galaxy);wrapper.style.position='relative';t826_runningAnimation(wrapper,options);return}
if(recIds){recIds=recIds.split(',');recIds.forEach(function(rec){var currentRec=document.querySelector('#rec'+rec);var currentGalaxy=galaxy.cloneNode(!0);currentGalaxy.style.position='absolute';t826_addAnimation(currentRec,currentGalaxy,options)})}else{var nextBlock;if(rec.nextElementSibling&&rec.nextElementSibling.querySelector('.t-cover')){nextBlock=rec.nextElementSibling}
var prevBlock;if(rec.previousElementSibling&&rec.previousElementSibling.querySelector('.t-cover')){prevBlock=rec.previousElementSibling}
var currentGalaxy=galaxy.cloneNode(!0);if(currentGalaxy)currentGalaxy.style.position='absolute';if(nextBlock){t826_addAnimation(nextBlock,currentGalaxy,options)}else if(prevBlock){t826_addAnimation(prevBlock,currentGalaxy,options)}}
if(wholePage==='yes'){var animationWrapper=rec.querySelector('.t826__animation');animationWrapper.style.display='block';galaxy.style.position='fixed';t826_addAnimation(allRecords,galaxy,options)}}
function t826_addAnimation(currentRec,galaxy,options){if(!currentRec)return;currentRec.setAttribute('data-animationappear','off');currentRec.classList.remove('r_hidden');var currentRecType=currentRec.getAttribute('data-record-type');var currentRecId=currentRec.getAttribute('id');if(currentRecType==='396'){var filter=currentRec.querySelector('.t396__filter');filter.insertAdjacentElement('afterend',galaxy);galaxy.style.zIndex='0'}else if(currentRecId==='allrecords'){galaxy.style.zIndex='-1'}else{var coverWrapper=currentRec.querySelector('.t-cover');if(coverWrapper){var filter=coverWrapper.querySelector('.t-cover__filter');filter.insertAdjacentElement('afterend',galaxy);galaxy.style.zIndex='0'}else{var wrapper=currentRec;if(wrapper.length===0){return!0}
wrapper.appendChild(galaxy);wrapper.style.position='relative';var excludesAboutBlocks=[480,478,477];var recordType=wrapper.getAttribute('data-record-type');var isBlockExclude=excludesAboutBlocks.some(function(block){return Number(recordType)===block});var firstChildDiv;if(isBlockExclude){firstChildDiv=wrapper.querySelector('.t'+recordType)}else{firstChildDiv=wrapper.querySelector('div')}
firstChildDiv.style.position='relative';firstChildDiv.style.zIndex='1';if(currentRecType=='734'||currentRecType=='675'||currentRecType=='215'){return}
var excludesBlocks=[754,776,778,786,770];if(excludesBlocks.indexOf(parseInt(currentRecType,10))!==-1){var firstChildDiv=wrapper.querySelector('div');firstChildDiv.style.zIndex='';galaxy.style.zIndex='-1'}else{galaxy.style.zIndex='0'}}}
t826_runningAnimation(currentRec,options)}
function t826_runningAnimation(currentRec,options){var starsSetting;if(window.isMobile){starsSetting=[{name:'near',count:25,speed:50},{name:'mid',count:50,speed:100},{name:'far',count:175,speed:150}]}else{starsSetting=[{name:'near',count:100,speed:50},{name:'mid',count:200,speed:100},{name:'far',count:700,speed:150}]}
var currentRecId=currentRec.getAttribute('id');var maxHeight=currentRec.offsetHeight;var maxWidth=currentRec.offsetWidth;if(typeof currentRecId==='undefined'){currentRecId='demo'}else if(currentRecId==='allrecords'){maxHeight=window.innerHeight;maxWidth=window.innerWidth}
var animationName='t826__galaxy-'+currentRecId;var animation=currentRec.querySelector('#'+animationName);if(animation&&animation.parentNode!==null){animation.parentNode.removeChild(animation)}
var newStyle=document.createElement('style');newStyle.id=animationName;newStyle.innerHTML='@keyframes '+animationName+'{'+'to{'+'transform:translateY('+(-maxHeight)+'px)'+'}'+'}';starsSetting.forEach(function(value,index,array){var x=Math.round(Math.random()*maxHeight);var y=Math.round(Math.random()*maxWidth);var dot='';if(options.color.indexOf('#')!==-1){dot=x+'px '+y+'px'}else if(options.opacity<1){dot=x+'px '+y+'px rgba('+options.color+','+options.opacity+')'}else{dot=x+'px '+y+'px rgb('+options.color+')'}
var countDots=Math.round(array[index].count*maxHeight/2000);for(var i=0;i<countDots;i++){var x=Math.round(Math.random()*maxWidth);var y=Math.round(Math.random()*maxHeight);if(options.color.indexOf('#')!==-1){dot+=', '+x+'px '+y+'px';dot+=', '+x+'px '+(y+maxHeight)+'px'}else if(options.opacity<1){dot+=', '+x+'px '+y+'px rgba('+options.color+','+options.opacity+')';dot+=', '+x+'px '+(y+maxHeight)+'px rgba('+options.color+','+options.opacity+')'}else{dot+=', '+x+'px '+y+'px rgb('+options.color+')';dot+=', '+x+'px '+(y+maxHeight)+'px rgb('+options.color+')'}}
var animationDuration=Math.round(array[index].speed*maxHeight/2000);var className='t826__galaxy-'+array[index].name+'-'+currentRecId;newStyle.innerHTML+='.'+className+':after, .'+className+'{'+'box-shadow:'+dot+';'+'animation-duration:'+animationDuration+'s;'+'animation-name:'+animationName+';'+(options.color.indexOf('#')!==-1?'color:'+options.color+';':'')+(options.color.indexOf('#')!==-1&&options.opacity<1?'opacity:'+options.opacity:'')+'}'+'.'+className+':after{'+"content:' ';"+'position:absolute;'+'top:'+maxHeight+'px'+'}';var galaxies=currentRec.querySelectorAll('.t826__galaxy > .t826__galaxy-wrapper > .t826__galaxy-'+array[index].name);Array.prototype.forEach.call(galaxies,function(galaxy){galaxy.classList.add(className)})});currentRec.insertAdjacentElement('afterbegin',newStyle);var galaxyWrappers=currentRec.querySelectorAll('.t826__galaxy > .t826__galaxy-wrapper');Array.prototype.forEach.call(galaxyWrappers,function(galaxy){galaxy.style.animationName='t826__galaxy-fadeIn'})}
function t849_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t849__accordion')[0];var headers=rec.querySelectorAll('.t849__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');if(accordion){accordion=accordion.getAttribute('data-accordion')}else{accordion='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;if(element.classList.contains('t849__opened')){element.classList.remove('t849__opened');t849_accordionHide(container)}else{if(accordion==='true'){t849_accordionAllHide(headers)}
element.classList.add('t849__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px'},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t849_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t849__opened');t849_accordionHide(elementHide.nextElementSibling)}}
function t849_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}}
function t886_init(recid){var el=$('#rec'+recid);var block=el.find('.t886');var closeBtn=el.find('.t886__btn');var storageItem=block.attr('data-storage-item');var lastOpen=null;if(typeof localStorage==='object'){try{lastOpen=localStorage.getItem(storageItem)}catch(e){console.log('Your web browser does not support localStorage.')}}
if(lastOpen==null){block.removeClass('t886_closed')}
closeBtn.click(function(e){block.addClass('t886_closed');if(typeof localStorage==='object'){try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(e){console.log('Your web browser does not support localStorage.')}}
e.preventDefault()})}